# This is a basic workflow to help you get started with Actions

name: PR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "Development" ]

jobs:
  development: 
    runs-on: wc
    environment: Dev
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Deploy Stage
      uses: Charan-SV/PR1@v1
      with:
          url: 'https://api.github.com/repos/DevGenius1/Charan-repo/pulls'
          method: 'POST'
          username: ${{ secrets.GUSERNAME }}
          password: ${{ secrets.PAT }}
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{ "title": "test-pr-dev", "body": "to test the auto pr", "head": "Development", "base": "stageing"}'

  prod:
      runs-on: LC
      needs: development
      environment: Prod
      steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Deploy Stage
        uses: Charan-SV/PR1@v1
        with:
            url: 'https://api.github.com/repos/DevGenius1/Charan-repo/pulls'
            method: 'POST'
            username: ${{ secrets.GUSERNAME }}
            password: ${{ secrets.PAT }}
            customHeaders: '{"Content-Type": "application/json"}'
            data: '{ "title": "test-pr-prod", "body": "to test the auto pr", "head": "Development", "base": "main"}'
      
