# This is a basic workflow to help you get started with Actions

name: PR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "Development" ]

jobs:
  deployment: 
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
          url: 'https://api.github.com/repos/DevGenius1/Test/pulls'
          method: 'POST'
          username: ${{ secrets.GUSERNAME }}
          password: ${{ secrets.PAT }}
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{ "title": "created by BOT", "body": "to test the auto pr", "head": "Development", "base": "main"}'
