name: status

on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
        
  jira:
    name: issue status transition
    needs: analyze
    if: ${{ always() }}
    runs-on: ubuntu-latest 

    steps:
       - name: rest api
         run: |
           curl -X POST https://bhavyass.atlassian.net/rest/api/2/issue/TS-2/transitions --user ${{ secrets.EMAIL }}:${{ secrets.JIRA_API_TOKEN }} -H 'Accept: application/json' -H 'Content-Type: application/json' -d '{
             "transition": {
               "id": "21"
             }
           }'
