name: status

on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
        
  jira:
    name: issue status transition
    needs: analyze
    if: ${{ always() }}
    runs-on: ubuntu-latest 

    steps:
       - name: rest api
         run: |
           curl -X POST https://bhavyass.atlassian.net/rest/api/2/issue/TS-2/transitions --user charanv@devtools.in:ATATT3xFfGF0K6v7T3btFUlpg4gu6bdXPzBkwURmytpl3nqt64mjXo4u_EBvaq2BmHvz8U-tUdLhjA4OUjwIBvnlboFKJm2c6iwC1c0CJ_2hfZYGT4PbCTGJpyaIZ0hPTSORde2NocEdQbq5VTwo47__7ryAhbpSpafvBEIlsGgZtL6uUjDDx18=14C4D5F7 -H 'Accept: application/json' -H 'Content-Type: application/json' -d '{
             "transition": {
               "id": "21"
             }
           }'
